services:
  - type: web
    name: servicios-app-backend
    env: node
    rootDir: servicios-app/backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && node dist/src/main.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servicios-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: servicios-db
